services:
  couchbase:
    image: couchbase:community
    container_name: couchbase
    ports:
      - "8091-8096:8091-8096"
      - "11210:11210"
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: Administrator
      COUCHBASE_ADMINISTRATOR_PASSWORD: password
      COUCHBASE_BUCKET: server_metrics
      COUCHBASE_BUCKET_RAMSIZE: 256
      COUCHBASE_BUCKET_TYPE: couchbase
      COUCHBASE_BUCKET_FLUSH_ENABLED: 1
      COUCHBASE_BUCKET_TTL: 300
    volumes:
      - couchbase_data:/opt/couchbase/var

volumes:
  couchbase_data:
